name: Development Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2

      - name: Install Deps
        run: |
          npm install

      - name: Run Tests
        run: |
          npm run test

      - name: Attempt Build
        run: |
          npm run build
